name: flutter_package_renamer
description: "A tool to rename flutter apps"
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  process_run:

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0

executables:
  rename: bin/rename.dart
  script: src/script.dart
  run_update_config: bin/run_update_config.dart

flutter:
  assets:
    - scripts/update_config.sh
